project:
  type: website
  output-dir: docs

website:
  title: MINI
  description: "Modular Independent Neovim Improvements"
  site-url: https://nvim-mini.org
  repo-url: https://github.com/nvim-mini
  favicon: /assets/logo-mini_180x180.png

  open-graph:
    image: /assets/logo-mini_social.png
  twitter-card:
    image: /assets/logo-mini_social.png

  navbar:
    search: true
    left:
      - href: mini.nvim/index.md
        text: mini.nvim
      - href: MiniMax/index.md
        text: MiniMax
      - href: blog/index.qmd
        text: Blog
    right:
      - icon: github
        href: https://github.com/nvim-mini
      - icon: rss-fill
        href: blog/index.xml
        aria-label: RSS

  page-footer:
    center: "© Evgeni Chasnovski, [MIT](https://choosealicense.com/licenses/mit/)"

  search:
    show-item-context: tree

format:
  html:
    theme:
      dark:
        - default
        - brand
      light:
        - default
        - brand
    toc: true
    respect-user-color-scheme: true
    code-overflow: scroll
    highlight-style:
      dark: theme/miniwinter-dark.theme
      light: theme/minisummer-light.theme
    include-after-body: assets/traffic-counter.html

brand:
  light: theme/brand-light.yml
  dark: theme/brand-dark.yml

execute:
  freeze: true
