---
title: "Moving from `nvim-0.12` to `nvim-0.13`"
---

_Generated from the `main` branch of 'MiniMax'_

### Moving from `nvim-0.12` to `nvim-0.13`

This page shows changes when moving from config [`nvim-0.12`](../../nvim-0.12/index.qmd) to config [`nvim-0.13`](../../nvim-0.13/index.qmd).
They are broken down into per-file differences that are shown in the [unified `diff` format](https://en.wikipedia.org/wiki/Diff#Unified_format).
The suggested usage is to consult this page when updating from `nvim-0.12` to `nvim-0.13` to see what is new.

In short:

- Lines with `@` show line numbers of where the change is made.
- Lines with `-` are removed from `nvim-0.12` config file.
- Lines with `+` are added into `nvim-0.13` config file.

#### init.lua {#init.lua}

<details><summary>Diff</summary>

```diffhunks
@@ -0,0 +1,5 @@
+-- WARNING: NEOVIM 0.13 IS STILL UNDER DEVELOPMENT AND NOT YET STABLE.
+-- BE SURE YOU ARE COMFORTABLE WITH KEEPING UP TO DATE DEVELOPMENT VERSION.
+-- THIS CONFIG IS VERIFIED FOR AT LEAST VERSION `v0.13.0-dev-29+g1bcf2d7f90`.
+-- WHEN IN DOUBT - UPDATE TO THE LATEST DEVELOPMENT VERSION.
+
```

</details>

#### nvim-pack-lock.json {#nvim-pack-lock.json}

No difference

#### plugin/10_options.lua {#plugin-10_options.lua}

No difference

#### plugin/20_keymaps.lua {#plugin-20_keymaps.lua}

No difference

#### plugin/30_mini.lua {#plugin-30_mini.lua}

No difference

#### plugin/40_plugins.lua {#plugin-40_plugins.lua}

No difference

#### snippets/global.json {#snippets-global.json}

No difference

#### after/ftplugin/markdown.lua {#after-ftplugin-markdown.lua}

No difference

#### after/lsp/lua_ls.lua {#after-lsp-lua_ls.lua}

No difference

#### after/snippets/lua.json {#after-snippets-lua.json}

No difference
