---
title: "Announcing 'mini.pick'"
author: Evgeni Chasnovski
date: 2023-10-13
categories: [announce, reddit]
description: Pick anything. Interactive non-blocking picker with one window design, toggleable preview, fast default matching, built-in pickers, and more
---

*Originally [posted on Reddit](https://www.reddit.com/r/neovim/comments/176yv8g/minipick_pick_anything_interactive_nonblocking/)*

{{< video 2023-10-13-announce-mini-pick/demo.mp4 >}}

Hello, Neovim users!

I would like to invite you to celebrate a special day with a massive release of [mini.pick](https://github.com/nvim-mini/mini.nvim/blob/main/readmes/mini-pick.md) - new module of [mini.nvim](https://github.com/nvim-mini/mini.nvim). It can also be installed using [separate GitHub repository](https://github.com/nvim-mini/mini.pick).

------

First things first. Today is a special day because it marks two years since [the first public release of 'mini.nvim'](2021-10-13-announce-mini-nvim.qmd). It was a nerve wracking to make, but your continuous support for the past two years made it worth it.

------

Now about 'mini.pick'. It has [a long (and still not full) list of features](https://github.com/nvim-mini/mini.nvim/blob/main/readmes/mini-pick.md#features), but for a blog post I'll compress it a bit. From a bird's eye view, it is an ['nvim-telescope/telescope.nvim'](https://github.com/nvim-telescope/telescope.nvim) with **completely** different UI/UX, **fast** and slightly different default matching, and only a **handful** of built-in pickers. Considerably more pickers will be released in a next 'mini.nvim' module ('mini.extra' with some extra configurations for other modules). If you are completely happy with Telescope, there is not much reasons to switch (besides mentioned earlier). All I can say is that I am now Telescope-free for about a month and loving it.

This is definitely the most ambitious module in 'mini.nvim': 3000+ lines, around 5000 lines of tests with almost 300 cases. But this is the price to pay for flexibility and comfortable out of the box experience.

If you want to learn more, see [overview](https://github.com/nvim-mini/mini.nvim/blob/main/readmes/mini-pick.md#overview).

For full documentation see [help file](https://github.com/nvim-mini/mini.nvim/blob/main/doc/mini-pick.txt).

------

Please, check it out and tell me what you think! You can leave your suggestions either here in comments or in [dedicated beta-testing issue](https://github.com/nvim-mini/mini.nvim/issues/513).

Thanks!
