---
title: "Announcing 'mini.notify'"
author: Evgeni Chasnovski
date: 2024-01-04
categories: [announce, reddit]
description: Show notifications. A `vim.notify()` maker plus automated LSP progress notifications
---

*Originally [posted on Reddit](https://www.reddit.com/r/neovim/comments/18ye17d/mininotify_show_notifications_a_vimnotify_maker/)*

{{< video 2024-01-04-announce-mini-notify/demo.mp4 >}}

Hello, Neovim users!

Please join me in welcoming 2024 with announce of [mini.notify](https://github.com/nvim-mini/mini.nvim/blob/main/readmes/mini-notify.md) - new module of [mini.nvim](https://github.com/nvim-mini/mini.nvim) with functionality to show one or more highlighted notifications in a floating window. It can also be installed using [separate GitHub repository](https://github.com/nvim-mini/mini.notify).

------

I personally didn't use fancy notifications before 'mini.notify' but it was on my TODO list. Recently it occurred to me that a demo of at least one upcoming module will look more interesting if several notifications can be shown at once. Thus I decided to move this new functionality up in list and here we are.

------

Features:

- Show one or more highlighted notifications in a single floating window.

- Manage notifications (add, update, remove, clear).

- `vim.notify()` wrapper generator (see [MiniNotify.make_notify()](https://github.com/nvim-mini/mini.nvim/blob/a118a964c94543c06d8b1f2f7542535dd2e19d36/doc/mini-notify.txt#L204)).

- Automated show of LSP progress report.

- Track history which can be accessed with `MiniNotify.get_all()` and shown with `MiniNotify.show_history()`.

For full documentation see [help file](https://github.com/nvim-mini/mini.nvim/blob/main/doc/mini-notify.txt).

------

Please, check it out and tell me what you think! You can leave your suggestions either here in comments or in [dedicated beta-testing issue](https://github.com/nvim-mini/mini.nvim/issues/640).

Thanks!
