---
title: "Minimax - Neovim with maximum MINI"
author: Evgeni Chasnovski
date: 2025-10-13
categories: [announce]
description: "MiniMax is an official config that mostly uses MINI tools"
---

Hello, Neovim users!

It is a huge joy and relief to be able to announce: there is now an "official" MINI config example. It is called [MiniMax](../MiniMax/index.md).

This release makes today a triple MINI birthday:

- The 'mini.nvim' plugin itself was released [four years ago](2021-10-13-announce-mini-nvim.qmd).
- The 'mini.pick' module was released [two years ago](2023-10-13-announce-mini-pick.qmd).
- And MiniMax now also has today as its birthday.

---

MiniMax is designed to be more than a single config. It is a [collection of configs](../MiniMax/configs/index.md), each specially crafted for specific conditions. Currently it is planned to have a dedicated config for each stable Neovim release, but other conditions are possible (but probably not in the near future). As far as I know, this type of arrangement is pretty unique to others "preconfigured configurations". It would make MiniMax useful beyond just configs: with time it might become a good reference for which changes are worth having when changing Neovim versions.

Configs themselves are fairly minimal in structure: small 'init.lua' and four 'plugin/' files that are loaded at startup. Their structure and contents are based on my own config that I've been daily driving for a very long time.

In today's terms, MiniMax is similar to 'nvim-lua/kickstart.nvim' in its style. Config files contain a lot of documentation comments and **are meant to be read**. Once you set up MiniMax, it is also up to you to update it. It is [not a distro and not a comprehensive guide for everything Neovim](../MiniMax/index.md#what-it-is-not)

---

I would also like to thank [Pete Kazmier](https://github.com/pkazmier) for all the helpful feedback during MiniMax development.

And thank *you all* for your continuous support! Let's hope to meet again for many more such birthdays to come!
