{
  "metadata": {
    "copyright": ["2025 Evgeni Chasnovski <evgeni.chasnovski@gmail.com>"],
    "license": "MIT",
    "name": "Seabed Dark"
  },
  "background-color": "#E5E2DB",
  "text-styles": {
    "Normal": {
      "text-color": "#222222",
      "selected-text-color": "#222222",
      "bold": false,
      "italic": false,
      "underline": false,
      "strike-through": false
    },
    "Keyword": {
      "text-color": "#222222",
      "selected-text-color": "#222222",
      "bold": true
    },
    "Function": {
      "text-color": "#006699",
      "selected-text-color": "#006699"
    },
    "Variable": {
      "text-color": "#222222",
      "selected-text-color": "#222222"
    },
    "ControlFlow": {
      "text-color": "#222222",
      "selected-text-color": "#222222",
      "bold": true
    },
    "Operator": {
      "text-color": "#626200",
      "selected-text-color": "#626200"
    },
    "BuiltIn": {
      "text-color": "#008064",
      "selected-text-color": "#008064"
    },
    "Extension": {
      "text-color": "#008064",
      "selected-text-color": "#008064",
      "bold": true
    },
    "Preprocessor": {
      "text-color": "#006699",
      "selected-text-color": "#006699"
    },
    "Attribute": {
      "text-color": "#006699",
      "selected-text-color": "#006699"
    },
    "Char": {
      "text-color": "#1D7300",
      "selected-text-color": "#1D7300"
    },
    "SpecialChar": {
      "text-color": "#626200",
      "selected-text-color": "#626200"
    },
    "String": {
      "text-color": "#1D7300",
      "selected-text-color": "#1D7300"
    },
    "VerbatimString": {
      "text-color": "#1D7300",
      "selected-text-color": "#1D7300"
    },
    "SpecialString": {
      "text-color": "#1D7300",
      "selected-text-color": "#1D7300"
    },
    "Import": {
      "text-color": "#1D7300",
      "selected-text-color": "#1D7300"
    },
    "DataType": {
      "text-color": "#780D60",
      "selected-text-color": "#780D60"
    },
    "DecVal": {
      "text-color": "#780D60",
      "selected-text-color": "#780D60"
    },
    "BaseN": {
      "text-color": "#780D60",
      "selected-text-color": "#780D60"
    },
    "Float": {
      "text-color": "#780D60",
      "selected-text-color": "#780D60"
    },
    "Constant": {
      "text-color": "#008064",
      "selected-text-color": "#008064",
      "bold": true
    },
    "Comment": {
      "text-color": "#6C7285",
      "selected-text-color": "#6C7285"
    },
    "Documentation": {
      "text-color": "#6C7285",
      "selected-text-color": "#6C7285"
    },
    "Annotation": {
      "text-color": "#870600",
      "selected-text-color": "#870600"
    },
    "CommentVar": {
      "text-color": "#008064",
      "selected-text-color": "#008064"
    },
    "RegionMarker": {
      "text-color": "#6C7285",
      "selected-text-color": "#6C7285"
    },
    "Information": {
      "text-color": "#006699",
      "selected-text-color": "#006699"
    },
    "Warning": {
      "text-color": "#626200",
      "selected-text-color": "#626200"
    },
    "Alert": {
      "text-color": "#626200",
      "selected-text-color": "#626200",
      "bold": true
    },
    "Error": {
      "text-color": "#870600",
      "selected-text-color": "#870600",
      "underline": true
    },
    "Others": {
      "text-color": "#222222",
      "selected-text-color": "#222222"
    }
  },
  "custom-styles": {
    "Diff": {
      "Removed line": {
        "text-color": "#870600",
        "selected-text-color": "#870600"
      },
      "Added line": {
        "text-color": "#1D7300",
        "selected-text-color": "#1D7300"
      }
    },
    "DiffHunks": {
      "Header": {
        "text-color": "#780D60",
        "selected-text-color": "#780D60"
      },
      "Removed": {
        "text-color": "#870600",
        "selected-text-color": "#870600"
      },
      "Added": {
        "text-color": "#1D7300",
        "selected-text-color": "#1D7300"
      },
      "Other": {
        "text-color": "#6C7285",
        "selected-text-color": "#6C7285"
      }
    }
  }
}
